### ISSUE TITLE
Default deployment is broken on AKS clusters

### ISSUE THREAD

**Issue by lcharlois-neotys** [Neotys-Labs/helm-neoload-web#53]
On AKS cluster, it looks like the default vlaue for `securityContext.runAsGroup` value is `1000`.
 Deploying the chart with default settings on AKS fails with the following error:

```
At least one application has been not deployed successfully, stopping server...
java.lang.IllegalStateException: Unable to create temp dir /server/work/nlweb-xxxxxxxxxxxxxx-deployment-4.3.6.war0
	at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:540)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:424)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:140)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:517)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:157)
	at com.neotys.vertx.jettyserver.provider.OrderedAppProvider.lambda$doStart$0(OrderedAppProvider.java:38)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.neotys.vertx.jettyserver.provider.OrderedAppProvider.doStart(OrderedAppProvider.java:38)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
2024-03-11 14:14:53,952 [main] WARN  o.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@faa3fed{nlweb-front-onpremise-deployment-4.3.6.war,/,null,STOPPED}{/server/wars/nlweb-front-onpremise-deployment-4.3.6.war}
```

Are images are expecting the user running the container to be member of group `0`.
This needs to be investigated and certainly need to change the way our image are built.
But changing images will certainly breaks compatibility with existing deployments.

**Comment by lcharlois-neotys** [comment]
This doesn't looks to be an AKS default settings but moreover a customer specific setting.
Closing this and creating #54 trying to propose a more global approach.
